// Première Partie

document.getElementById('couleur').style.color="orange";

document.getElementById('color').style.color="orange"; //Ou getElementsByClassName('')

document.getElementById('couleur').style.display="inline";

document.getElementById('color').style.cssFloat="right";


// Deuxième Partie

document.querySelector("article div").style.display="inline";

document.querySelector("article DIV:nth-child(2)").style.display="inline";

document.querySelector("article DIV:nth-child(3)").style.display="inline";

document.querySelector("article div").style.color="red";

document.querySelector("article DIV:nth-child(2)").style.color="green";

document.querySelector("article DIV:nth-child(3)").style.color="blue"; 